on: [push]

name: CI

jobs:
  maven:
    needs:
      - windows_x64
      - linux_x64
      - linux_arm
    name: Maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: leveldb-mcpe.dll
          path: src/main/resources
      - uses: actions/download-artifact@master
        with:
          name: libleveldb-mcpe.so
          path: src/main/resources
      - uses: actions/download-artifact@master
        with:
          name: libleveldb-mcpe_arm.so
          path: src/main/resources
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish package
        run: mvn -B deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
  linux_x64:
    name: Linux x64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y zlib1g-dev
      - run: chmod +x ./compile.sh && ./compile.sh
      - uses: actions/upload-artifact@master
        with:
          name: libleveldb-mcpe.so
          path: src/main/c/libleveldb-mcpe.so
  linux_arm:
    name: Linux ARM
    runs-on: ARM
    steps:
      - uses: actions/checkout@v2
      - run: chmod +x ./compile.sh && ./compile.sh
      - run: mv src/main/c/libleveldb-mcpe.so src/main/c/libleveldb-mcpe_arm.so
      - uses: actions/upload-artifact@master
        with:
          name: libleveldb-mcpe_arm.so
          path: src/main/c/libleveldb-mcpe_arm.so
  windows_x64:
    name: Windows x64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: choco install wget
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
      - run: ./compile.bat
      - uses: actions/upload-artifact@master
        with:
          name: leveldb-mcpe.dll
          path: src/main/c/Release/leveldb-mcpe.dll
