on: [push]

name: CI

jobs:
  windows_x64:
    name: Windows x64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: choco install wget
      - run: ./compile.bat
      - uses: actions/upload-artifact@master
        with:
          name: leveldb-mcpe.dll
          path: src/main/c/Release/leveldb-mcpe.dll
