on: [push]

name: CI

jobs:
  linux_x64:
    name: Linux x64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y zlib1g-dev
      - run: chmod +x ./compile.sh && ./compile.sh
      - uses: actions/upload-artifact@master
        with:
          name: libleveldb-mcpe.so
          path: src/main/c/libleveldb-mcpe.so
  windows_x64:
    name: Windows x64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: choco install wget
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.1
      - run: ./compile.bat
      - uses: actions/upload-artifact@master
        with:
          name: leveldb-mcpe.dll
          path: src/main/c/Release/leveldb-mcpe.dll
